title: DozeInject
description: Cybersecurity notes, web security labs and CTF writeups

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-feed
  - jekyll-include-cache

markdown: kramdown

permalink: /:year/:month/:day/:title/
minimal_mistakes_skin: "dark"
title_separator: "|"
